# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Home CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build:types
      - run: pnpm run build:client
      - run: pnpm run build:server
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'dist/'
          REMOTE_HOST: 122.51.147.253
          REMOTE_USER: root
          REMOTE_PORT: 222
          TARGET: /home/soft/cmes
          SCRIPT_AFTER: lsof -i :3100 -t | xargs kill -9 && sh /www/server/nodejs/vhost/scripts/cmes.sh
